
FROM node:18-alpine

WORKDIR /app

COPY package.json ./ 

COPY package-lock.json ./ 

RUN npm install

COPY . .

WORKDIR /app/src

ENV DBURL = "https://noventiq-exercise-db-default-rtdb.asia-southeast1.firebasedatabase.app/"

EXPOSE 3001

CMD ["node", "server.js"]


